/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { FirebaseDevice } from '../models';
import { FirebaseDeviceSerializerWithOwnersResponse } from '../models';
import { URLSearchParams, URL } from 'url';
/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new FirebaseDevice. If uuid is not provided a new device will be created. If a uuid for an existing Safe is provided the FirebaseDevice will be updated with all the new data provided. Safes provided on the request are always added and never removed/replaced
         * @param {FirebaseDevice} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesCreate: async (body: FirebaseDevice, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling notificationsDevicesCreate.');
            }
            const localVarPath = `/notifications/devices/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a FirebaseDevice
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesDelete: async (uuid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            if (uuid === null || uuid === undefined) {
                throw new RequiredError('uuid','Required parameter uuid was null or undefined when calling notificationsDevicesDelete.');
            }
            const localVarPath = `/notifications/devices/{uuid}/`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a Safe for a FirebaseDevice
         * @param {string} address 
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesSafesDelete: async (address: string, uuid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling notificationsDevicesSafesDelete.');
            }
            // verify required parameter 'uuid' is not null or undefined
            if (uuid === null || uuid === undefined) {
                throw new RequiredError('uuid','Required parameter uuid was null or undefined when calling notificationsDevicesSafesDelete.');
            }
            const localVarPath = `/notifications/devices/{uuid}/safes/{address}/`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)))
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 * @export
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a new FirebaseDevice. If uuid is not provided a new device will be created. If a uuid for an existing Safe is provided the FirebaseDevice will be updated with all the new data provided. Safes provided on the request are always added and never removed/replaced
         * @param {FirebaseDevice} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsDevicesCreate(body: FirebaseDevice, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FirebaseDeviceSerializerWithOwnersResponse>> {
            const localVarAxiosArgs = await NotificationsApiAxiosParamCreator(configuration).notificationsDevicesCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Remove a FirebaseDevice
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsDevicesDelete(uuid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await NotificationsApiAxiosParamCreator(configuration).notificationsDevicesDelete(uuid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Remove a Safe for a FirebaseDevice
         * @param {string} address 
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsDevicesSafesDelete(address: string, uuid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await NotificationsApiAxiosParamCreator(configuration).notificationsDevicesSafesDelete(address, uuid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NotificationsApi - factory interface
 * @export
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a new FirebaseDevice. If uuid is not provided a new device will be created. If a uuid for an existing Safe is provided the FirebaseDevice will be updated with all the new data provided. Safes provided on the request are always added and never removed/replaced
         * @param {FirebaseDevice} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesCreate(body: FirebaseDevice, options?: any): AxiosPromise<FirebaseDeviceSerializerWithOwnersResponse> {
            return NotificationsApiFp(configuration).notificationsDevicesCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a FirebaseDevice
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesDelete(uuid: string, options?: any): AxiosPromise<void> {
            return NotificationsApiFp(configuration).notificationsDevicesDelete(uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a Safe for a FirebaseDevice
         * @param {string} address 
         * @param {string} uuid A UUID string identifying this Firebase Device.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsDevicesSafesDelete(address: string, uuid: string, options?: any): AxiosPromise<void> {
            return NotificationsApiFp(configuration).notificationsDevicesSafesDelete(address, uuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export class NotificationsApi extends BaseAPI {
    /**
     * Creates a new FirebaseDevice. If uuid is not provided a new device will be created. If a uuid for an existing Safe is provided the FirebaseDevice will be updated with all the new data provided. Safes provided on the request are always added and never removed/replaced
     * @param {FirebaseDevice} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationsDevicesCreate(body: FirebaseDevice, options?: any) {
        return NotificationsApiFp(this.configuration).notificationsDevicesCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a FirebaseDevice
     * @param {string} uuid A UUID string identifying this Firebase Device.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationsDevicesDelete(uuid: string, options?: any) {
        return NotificationsApiFp(this.configuration).notificationsDevicesDelete(uuid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a Safe for a FirebaseDevice
     * @param {string} address 
     * @param {string} uuid A UUID string identifying this Firebase Device.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationsDevicesSafesDelete(address: string, uuid: string, options?: any) {
        return NotificationsApiFp(this.configuration).notificationsDevicesSafesDelete(address, uuid, options).then((request) => request(this.axios, this.basePath));
    }
}
