/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { SafeMultisigTransactionResponse } from '../models';
import { URLSearchParams, URL } from 'url';

/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} safeTxHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsRead: async (safeTxHash: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'safeTxHash' is not null or undefined
            if (safeTxHash === null || safeTxHash === undefined) {
                throw new RequiredError('safeTxHash','Required parameter safeTxHash was null or undefined when calling transactionsRead.');
            }
            const localVarPath = `/transactions/{safe_tx_hash}/`
                .replace(`{${"safe_tx_hash"}}`, encodeURIComponent(String(safeTxHash)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} safeTxHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsRead(safeTxHash: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SafeMultisigTransactionResponse>> {
            const localVarAxiosArgs = await TransactionsApiAxiosParamCreator(configuration).transactionsRead(safeTxHash, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} safeTxHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsRead(safeTxHash: string, options?: any): AxiosPromise<SafeMultisigTransactionResponse> {
            return TransactionsApiFp(configuration).transactionsRead(safeTxHash, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
    /**
     * 
     * @param {string} safeTxHash 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public transactionsRead(safeTxHash: string, options?: any) {
        return TransactionsApiFp(this.configuration).transactionsRead(safeTxHash, options).then((request) => request(this.axios, this.basePath));
    }
}
