/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AllTransactionsSchema
 */
export interface AllTransactionsSchema {
    /**
     * 
     * @type {SafeModuleTransactionWithTransfersResponse}
     * @memberof AllTransactionsSchema
     */
    txType1: any;
    /**
     * 
     * @type {SafeMultisigTransactionWithTransfersResponse}
     * @memberof AllTransactionsSchema
     */
    txType2: any;
    /**
     * 
     * @type {EthereumTxWithTransfersResponse}
     * @memberof AllTransactionsSchema
     */
    txType3: any;
}
