/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ContractAbi
 */
export interface ContractAbi {
    /**
     * 
     * @type {Array&lt;{ [key, string]: string;}&gt;}
     * @memberof ContractAbi
     */
    abi: any;
    /**
     * 
     * @type {string}
     * @memberof ContractAbi
     */
    description: any;
    /**
     * 
     * @type {number}
     * @memberof ContractAbi
     */
    relevance: any;
}
