/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Erc20Info
 */
export interface Erc20Info {
    /**
     * 
     * @type {string}
     * @memberof Erc20Info
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof Erc20Info
     */
    symbol: any;
    /**
     * 
     * @type {number}
     * @memberof Erc20Info
     */
    decimals: any;
    /**
     * 
     * @type {string}
     * @memberof Erc20Info
     */
    logoUri: any;
}
