/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FirebaseDevice
 */
export interface FirebaseDevice {
    /**
     * 
     * @type {string}
     * @memberof FirebaseDevice
     */
    uuid?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof FirebaseDevice
     */
    safes: any;
    /**
     * 
     * @type {string}
     * @memberof FirebaseDevice
     */
    cloudMessagingToken: any;
    /**
     * 
     * @type {number}
     * @memberof FirebaseDevice
     */
    buildNumber: any;
    /**
     * 
     * @type {string}
     * @memberof FirebaseDevice
     */
    bundle: any;
    /**
     * 
     * @type {string}
     * @memberof FirebaseDevice
     */
    deviceType: FirebaseDeviceDeviceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FirebaseDevice
     */
    version: any;
    /**
     * 
     * @type {number}
     * @memberof FirebaseDevice
     */
    timestamp?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof FirebaseDevice
     */
    signatures?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum FirebaseDeviceDeviceTypeEnum {
    ANDROID = 'ANDROID',
    IOS = 'IOS',
    WEB = 'WEB'
}

