/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MasterCopyResponse
 */
export interface MasterCopyResponse {
    /**
     * 
     * @type {string}
     * @memberof MasterCopyResponse
     */
    address: any;
    /**
     * 
     * @type {string}
     * @memberof MasterCopyResponse
     */
    version: any;
    /**
     * 
     * @type {string}
     * @memberof MasterCopyResponse
     */
    deployer: any;
    /**
     * 
     * @type {number}
     * @memberof MasterCopyResponse
     */
    deployedBlockNumber: any;
    /**
     * 
     * @type {number}
     * @memberof MasterCopyResponse
     */
    lastIndexedBlockNumber: any;
}
