/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeInfoResponse
 */
export interface SafeInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof SafeInfoResponse
     */
    address: any;
    /**
     * 
     * @type {number}
     * @memberof SafeInfoResponse
     */
    nonce: any;
    /**
     * 
     * @type {number}
     * @memberof SafeInfoResponse
     */
    threshold: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SafeInfoResponse
     */
    owners: any;
    /**
     * 
     * @type {string}
     * @memberof SafeInfoResponse
     */
    masterCopy: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SafeInfoResponse
     */
    modules: any;
    /**
     * 
     * @type {string}
     * @memberof SafeInfoResponse
     */
    fallbackHandler: any;
    /**
     * 
     * @type {string}
     * @memberof SafeInfoResponse
     */
    guard: any;
    /**
     * 
     * @type {string}
     * @memberof SafeInfoResponse
     */
    version: any;
}
