/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeBalanceUsdResponse
 */
export interface SafeBalanceUsdResponse {
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    tokenAddress: any;
    /**
     * 
     * @type {Erc20Info}
     * @memberof SafeBalanceUsdResponse
     */
    token: any;
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    balance: any;
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    ethValue: any;
    /**
     * 
     * @type {Date}
     * @memberof SafeBalanceUsdResponse
     */
    timestamp: any;
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    fiatBalance: any;
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    fiatConversion: any;
    /**
     * 
     * @type {string}
     * @memberof SafeBalanceUsdResponse
     */
    fiatCode: any;
}
