/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeCreationInfoResponse
 */
export interface SafeCreationInfoResponse {
    /**
     * 
     * @type {Date}
     * @memberof SafeCreationInfoResponse
     */
    created: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    creator: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    transactionHash: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    factoryAddress: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    masterCopy: any | null;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    setupData: any | null;
    /**
     * 
     * @type {string}
     * @memberof SafeCreationInfoResponse
     */
    dataDecoded?: any;
}
