/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeModuleTransactionResponse
 */
export interface SafeModuleTransactionResponse {
    /**
     * 
     * @type {Date}
     * @memberof SafeModuleTransactionResponse
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof SafeModuleTransactionResponse
     */
    executionDate: any;
    /**
     * 
     * @type {number}
     * @memberof SafeModuleTransactionResponse
     */
    blockNumber?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SafeModuleTransactionResponse
     */
    isSuccessful?: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    transactionHash?: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    safe: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    module: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    to: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    value: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    data: any | null;
    /**
     * 
     * @type {number}
     * @memberof SafeModuleTransactionResponse
     */
    operation: any;
    /**
     * 
     * @type {string}
     * @memberof SafeModuleTransactionResponse
     */
    dataDecoded?: any;
}
