/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeMultisigTransactionEstimate
 */
export interface SafeMultisigTransactionEstimate {
    /**
     * 
     * @type {string}
     * @memberof SafeMultisigTransactionEstimate
     */
    to: any;
    /**
     * 
     * @type {number}
     * @memberof SafeMultisigTransactionEstimate
     */
    value: any;
    /**
     * 
     * @type {string}
     * @memberof SafeMultisigTransactionEstimate
     */
    data?: any | null;
    /**
     * 
     * @type {number}
     * @memberof SafeMultisigTransactionEstimate
     */
    operation: any;
}
