/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SafeCollectibleResponse
 */
export interface SafeCollectibleResponse {
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    address: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    tokenName: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    tokenSymbol: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    logoUri: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    uri: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    description: any;
    /**
     * 
     * @type {string}
     * @memberof SafeCollectibleResponse
     */
    imageUri: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof SafeCollectibleResponse
     */
    metadata: any;
}
