/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenInfoResponse
 */
export interface TokenInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenInfoResponse
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof TokenInfoResponse
     */
    address: any;
    /**
     * 
     * @type {string}
     * @memberof TokenInfoResponse
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof TokenInfoResponse
     */
    symbol: any;
    /**
     * 
     * @type {number}
     * @memberof TokenInfoResponse
     */
    decimals: any;
    /**
     * 
     * @type {string}
     * @memberof TokenInfoResponse
     */
    logoUri?: any;
}
