/* tslint:disable */
/* eslint-disable */
/**
 * Gnosis Safe Transaction Service API
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * OpenAPI spec version: v1
 * Contact: safe@gnosis.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransferResponse
 */
export interface TransferResponse {
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    type?: any;
    /**
     * 
     * @type {Date}
     * @memberof TransferResponse
     */
    executionDate: any;
    /**
     * 
     * @type {number}
     * @memberof TransferResponse
     */
    blockNumber: any;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    transactionHash: any;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    to: any;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    value: any | null;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    tokenId: any | null;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    tokenAddress?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TransferResponse
     */
    from: any;
}
